---
kind: Service
apiVersion: v1
metadata:
  name: logstash
spec:
  type: LoadBalancer
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
    name: filebeat
  - protocol: TCP
    port: 9600
    targetPort: 9600
    name: logstash